spring.jpa.open-in-view=false
spring.application.name=dietpet-backend
spring.config.import=optional:file:.env[.properties]
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.datasource.url=jdbc:postgresql://localhost:5433/diet_pet
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
